### PR TITLE
random_bytes

### PR DESCRIPTION
**Pull request by a-chol**
# a-chol's Submission for Business Card Event 2020

A random keystrokes generator business card, based on a hardware Random Number Generator.

- [X ] By checking this box I agree that this board was made within the April 4th - May 31st time and if it was not I agree to forfeit any prize I may or may not win.

### CODE REVIEW

**Comment by LostQuasar** [comment]
This looks good but id prefer if you used Imgur to host your images instead of uploading them here

**Comment by a-chol** [comment]
No problem, done.
By the way, I seem to not have permissions to post on the discord like others. Do I have to register in some specific way?

**Comment by LostQuasar** [comment]
Make sure you type ?verify in the verification channel, the bot might be down. tell me your username and ill give ya the role
EDIT: Also make sure you delete the image since you are hosting on Imgur

**Comment by a-chol** [comment]
You're right, I forgot deleting the images. I'll do it right away. Btw, the ?verify worked in the verification channel, sorry I didn't know about that feature.

**Comment by LostQuasar** [comment]
No worries glad you got it worked out

**Pull request merged**
