### PR TITLE
Crokto

### PR DESCRIPTION
**Pull request by Croktopus**
# Crokto's Submission for Business Card Event 2020

Gameboy controller

- [X] By checking this box I agree that this board was made within the April 4th - May 31st time and if it was not I agree to forfeit any prize I may or may not win.

### CODE REVIEW

**Review by LostQuasar — CHANGES_REQUESTED** [review]
Please remove all unused footprints

**Comment by Kyrremann** [comment]
Are there no images? Didn't see anyone in the README.md file

**Comment by Croktopus** [comment]
alright finally got around to switching it to the real submission lol. i think everything should be in there now

**Comment by LostQuasar** [comment]
One more thing i need you to remove images and host them externally (Imgur)

**Comment by Croktopus** [comment]
should be done!

**Pull request merged**
